version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: bugtracker_postgres
    restart: always
    environment:
      POSTGRES_DB: bugtracker
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bugtracker_api
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}

volumes:
  postgres_data: