spring.datasource.url=jdbc:postgresql://localhost:5432/bugtracker
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=73DJTL9ytn0Ed6Psm2yEj2NhUBNd72pWulj7AmJ5gxo=
jwt.expiration=86400000